name: bkey_user
description: "A new Flutter project."
version: 7.6.7+17

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.1
  go_router: ^16.2.5
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.1
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/bkey-get.png"
  background_color: "#005842"
  adaptive_icon_background: "#005842"
  adaptive_icon_foreground: "assets/images/bkey-get.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
